name: Build Packages

on:
  workflow_dispatch: # 保留手动触发选项
  pull_request:
    types: [closed]
    branches:
      - Alpha # 或者你的默认分支名，如 master

jobs:
  check_pr_merge:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    steps:
      - name: Check PR title
        id: check_title
        run: |
          if [[ "${{ github.event.pull_request.title }}" == "Update Mihomo Package Hash" ]]; then
            echo "SHOULD_BUILD=true" >> $GITHUB_OUTPUT
          else
            echo "SHOULD_BUILD=false" >> $GITHUB_OUTPUT
          fi

  build:
    needs: check_pr_merge
    if: needs.check_pr_merge.outputs.SHOULD_BUILD == 'true'
    name: ${{ matrix.arch }}-${{ matrix.release }} build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        arch:
          - aarch64_generic
        release:
          - openwrt-23.05

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Build
        uses: ForestL18/gh-action-sdk@main
        env:
          ARCH: ${{ matrix.arch }}-${{ matrix.release }}
          FEEDNAME: mihomo_openwrt
          PACKAGES: luci-app-mihomo
          NO_REFRESH_CHECK: true

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.arch }}-${{ matrix.release }}
          path: bin/packages/${{ matrix.arch }}/mihomo_openwrt/*.ipk
