name: Sync Upstream and Create PR

on:
  schedule:
    - cron: "0 17 * * *" # 每天 UTC+8 时间 01:00 运行
  workflow_dispatch: # 允许手动触发

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

      - name: Add Upstream Remote
        run: git remote add upstream https://github.com/morytyann/OpenWrt-mihomo.git

      - name: Setup Sparse Checkout
        run: |
          git config core.sparsecheckout true
          echo '*' > .git/info/sparse-checkout
          echo '!mihomo/Makefile' >> .git/info/sparse-checkout
          echo '!luci-app-mihomo/Makefile' >> .git/info/sparse-checkout
          echo '!.github/workflows' >> .git/info/sparse-checkout

      - name: Fetch Upstream
        run: git fetch upstream

      - name: Create Sync Branch
        run: |
          git checkout -b sync-upstream-changes
          git merge upstream/main --allow-unrelated-histories
          git push origin sync-upstream-changes

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: "Sync changes from upstream repository"
          body: |
            This PR syncs changes from the upstream repository.

            Changes excluded:
            - mihomo/Makefile
            - luci-app-mihomo/Makefile
            - .github/workflows/
          branch: sync-upstream-changes
          base: Alpha
          labels: automated-pr, sync
