name: Sync Upstream and Create PR

on:
  schedule:
    - cron: "0 17 * * *"
  workflow_dispatch:

jobs:
  sync-upstream:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Sync upstream repository
        run: |
          git remote add upstream https://github.com/morytyann/OpenWrt-mihomo.git
          git fetch upstream
          git read-tree --prefix=temp/ -u upstream/main
          git checkout HEAD -- mihomo/Makefile luci-app-mihomo/Makefile .github
          git read-tree --prefix=. -u HEAD
          git commit -m "Sync upstream"

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          title: Sync upstream and merge changes
          branch: sync-upstream
          body: |
            This PR syncs with the upstream repository and merges the changes.

            Ignored files:
            - `mihomo/Makefile`
            - `luci-app-mihomo/Makefile`

            Ignored directory:
            - `.github`
          delete-branch: true
