name: Sync Upstream and Create PR

on:
  schedule:
    - cron: "0 17 * * *" # 每天运行一次
  workflow_dispatch: # 允许手动触发

jobs:
  sync-upstream:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name 'GitHub Actions'
          git config user.email 'actions@github.com'

      - name: Fetch Upstream
        run: |
          git remote add upstream https://github.com/morytyann/OpenWrt-mihomo.git
          git fetch upstream

      - name: Merge Upstream
        run: |
          git merge --no-commit --no-ff upstream/main
          git status

      - name: Reset Excluded Files and Directory
        run: |
          git checkout HEAD -- mihomo/Makefile
          git checkout HEAD -- luci-app-mihomo/Makefile
          git checkout HEAD -- .github/workflows/
          git checkout HEAD -- mihomo/files/mihomo.init
          git status

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          title: Sync Upstream Changes
          body: |
            This PR syncs changes from the upstream repository.

            While preserving our local modifications as specified:
            - mihomo/Makefile,
            - luci-app-mihomo/Makefile,
            - .github/workflows/
          branch: sync-upstream
          base: Alpha
          #delete-branch: true
