name: Sync Upstream
on:
  schedule:
    - cron: "0 17 * * *" # 每天运行 01:00 AM UTC+8
  workflow_dispatch: # 允许手动触发
jobs:
  sync-upstream:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

      - name: Add Upstream Remote
        run: |
          git remote add upstream https://github.com/morytyann/OpenWrt-mihomo.git

      - name: Fetch Upstream
        run: |
          git fetch upstream

      - name: Switch to Target Branch
        run: |
          git checkout Alpha

      - name: Set up sparse-checkout
        run: |
          git config core.sparsecheckout true
          echo '/*' > .git/info/sparse-checkout
          echo '!mihomo/Makefile' >> .git/info/sparse-checkout
          echo '!luci-app-mihomo/Makefile' >> .git/info/sparse-checkout
          echo '!.github/workflows/' >> .git/info/sparse-checkout

      - name: Merge Upstream
        run: |
          git merge upstream/main --allow-unrelated-histories

      - name: Check for Changes
        id: check_changes
        run: |
          if git diff --quiet HEAD; then
            echo "changes_made=false" >> $GITHUB_OUTPUT
          else
            echo "changes_made=true" >> $GITHUB_OUTPUT
          fi

      - name: Create Pull Request
        if: steps.check_changes.outputs.changes_made == 'true'
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: Sync upstream changes
          title: Sync Upstream Changes
          body: |
            This PR syncs changes from the upstream repository.
            Automated changes by GitHub Actions.
          branch: sync-upstream-changes
          base: Alpha # 目标分支，保持与之前相同
          delete-branch: true

      - name: Check PR Status
        if: steps.check_changes.outputs.changes_made == 'true'
        run: |
          echo "Pull Request created successfully."
          
      - name: No Changes
        if: steps.check_changes.outputs.changes_made == 'false'
        run: |
          echo "No changes were made. The repository is already up to date."
