name: Sync Upstream and Create PR

on:
  schedule:
    - cron: "0 0 * * *" # 每天运行一次
  workflow_dispatch: # 允许手动触发

jobs:
  sync-upstream:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

      - name: Add Upstream Remote
        run: git remote add upstream https://github.com/morytyann/OpenWrt-mihomo.git

      - name: Configure Sparse Checkout
        run: |
          git config core.sparsecheckout true
          echo '/*' > .git/info/sparse-checkout
          echo '!mihomo/Makefile' >> .git/info/sparse-checkout
          echo '!luci-app-mihomo/Makefile' >> .git/info/sparse-checkout
          echo '!.github/workflows' >> .git/info/sparse-checkout

      - name: Fetch and Merge Upstream
        run: |
          git fetch upstream
          git checkout -b sync-upstream
          git merge upstream/main --allow-unrelated-histories

      - name: Push Changes
        run: git push origin sync-upstream

      - name: Create Pull Request
        uses: repo-sync/pull-request@v6
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          source_branch: "sync-upstream"
          destination_branch: "main"
          pr_title: "Sync: Merge upstream changes"
          pr_body: "Automated PR to sync changes from upstream repository"
