name: Sync Upstream and Create PR

on:
  schedule:
    - cron: "0 17 * * *" # 每天运行一次
  workflow_dispatch: # 允许手动触发

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Alpha branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: Alpha

      - name: Configure Git
        run: |
          git config user.name github-actions[bot]
          git config user.email github-actions[bot]@users.noreply.github.com

      - name: Add Upstream Remote
        run: git remote add upstream https://github.com/morytyann/OpenWrt-mihomo.git

      - name: Fetch Upstream
        run: git fetch upstream

      - name: Create Sync Branch
        run: git checkout -b sync-upstream-changes

      - name: Merge Upstream
        env:
          IGNORE_OPTIONS: -X ignore=mihomo/Makefile -X ignore=luci-app-mihomo/Makefile -X ignore=.github/workflows/
        run: |
          git merge upstream/main --no-commit --no-ff $IGNORE_OPTIONS
          git add .
          git diff --staged --quiet || git commit -m "Sync upstream changes"

      - name: Push New Branch
        run: git push origin sync-upstream-changes

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: "Sync changes from upstream repository"
          body: "This PR syncs changes from the upstream repository, excluding specified files and directories."
          branch: sync-upstream-changes
          base: Alpha
          labels: automated-pr, sync-upstream
