name: Sync Upstream Repository

on:
  schedule:
    - cron: "0 17 * * *" # 每天运行一次
  workflow_dispatch: # 手动触发

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout current repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false # 禁用自动提供的token
          fetch-depth: 0 # 获取所有历史记录

      - name: Add Upstream Remote
        run: git remote add upstream https://github.com/morytyann/OpenWrt-mihomo.git

      - name: Fetch Upstream Changes
        run: git fetch upstream

      - name: Checkout Upstream Branch
        run: git checkout upstream/main

      - name: Remove Ignored Files and Directory
        run: |
          rm -f mihomo/Makefile
          rm -f luci-app-mihomo/Makefile
          rm -rf .github/workflows

      - name: Commit Changes
        run: |
          git checkout -b sync-upstream
          git add .
          git commit -m "Sync with upstream and remove ignored files"

      - name: Push Changes to Origin
        run: git push -u origin sync-upstream

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          title: "Sync with upstream"
          body: "This PR syncs the latest changes from upstream, excluding specific files and directories."
          head: sync-upstream
          base: main
          branch: main
