name: Sync Upstream and Create PR

on:
  schedule:
    - cron: "0 0 * * *" # 每天运行
  workflow_dispatch: # 允许手动触发

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com

      - name: Add Upstream Remote
        run: git remote add upstream https://github.com/morytyann/OpenWrt-mihomo.git

      - name: Fetch Upstream
        run: git fetch upstream

      - name: Sync Upstream Changes
        run: |
          git merge -X theirs --no-edit upstream/main
          git reset upstream/main -- mihomo/Makefile luci-app-mihomo/Makefile .github/workflows
          git checkout -- mihomo/Makefile luci-app-mihomo/Makefile

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: Sync changes from upstream repository
          title: Sync Upstream Changes
          body: |
            This PR syncs changes from the upstream repository.

            Changes to the following files/directories were ignored:
            - mihomo/Makefile
            - luci-app-mihomo/Makefile
            - .github/workflows
          branch: sync-upstream
          base: main
          delete-branch: true
