name: Sync Upstream and Create PR

on:
  schedule:
    - cron: "0 0 * * *" # 每天UTC时间00:00运行
  workflow_dispatch: # 允许手动触发

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

      - name: Add Upstream Remote
        run: git remote add upstream https://github.com/morytyann/OpenWrt-mihomo.git

      - name: Fetch Upstream
        run: git fetch upstream

      - name: Merge Upstream
        run: |
          # 备份要保持不变的文件和目录
          cp mihomo/Makefile mihomo/Makefile.bak
          cp luci-app-mihomo/Makefile luci-app-mihomo/Makefile.bak
          cp -r .github/workflows .github/workflows.bak

          # 合并上游更改
          git merge -X theirs upstream/main --no-commit --no-ff

          # 恢复指定的文件和目录
          mv mihomo/Makefile.bak mihomo/Makefile
          mv luci-app-mihomo/Makefile.bak luci-app-mihomo/Makefile
          rm -rf .github/workflows
          mv .github/workflows.bak .github/workflows

          # 添加更改到暂存区
          git add .

          # 提交更改，如果有的话
          git diff --cached --quiet || git commit -m "Sync with upstream"

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: Sync upstream changes
          title: Sync changes from upstream repository
          body: |
            This PR syncs changes from the upstream repository.

            Changes have been merged excluding:
            - mihomo/Makefile
            - luci-app-mihomo/Makefile
            - .github/workflows directory
          branch: sync-upstream
          delete-branch: true
          base: Alpha
