name: Sync Upstream and Create PR

on:
  schedule:
    - cron: "0 17 * * *" # 每天午夜运行
  workflow_dispatch: # 允许手动触发

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name github-actions[bot]
          git config user.email github-actions[bot]@users.noreply.github.com

      - name: Add Upstream Remote
        run: git remote add upstream https://github.com/morytyann/OpenWrt-mihomo.git

      - name: Fetch Upstream
        run: git fetch upstream

      - name: Create Sync Branch
        run: git checkout -b sync-upstream-changes

      - name: Sync Upstream Changes
        run: |
          # 创建一个新的合并提交，但不自动提交
          git merge --no-commit --no-ff upstream/main

          # 使用 git read-tree 来更新工作目录，排除不想要的文件和目录
          git read-tree -mu HEAD:. upstream/main:. \
            ':!mihomo/Makefile' \
            ':!luci-app-mihomo/Makefile' \
            ':!.github/workflows'

          # 检查是否有变更
          if git diff --staged --quiet; then
            echo "No changes to commit."
            exit 0
          fi

          # 提交变更
          git commit -m "Sync upstream changes"

      - name: Push changes
        run: git push origin sync-upstream-changes

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: "Sync changes from upstream repository"
          body: |
            This PR syncs changes from the upstream repository.

            Changes exclude:
            - mihomo/Makefile
            - luci-app-mihomo/Makefile
            - .github/workflows/ directory

            Please review and merge.
          branch: sync-upstream-changes
          base: Alpha # 您的主分支名称，通常是 main 或 master
          labels: automated pr, sync
          draft: false
