name: Sync Upstream and Create PR

on:
  schedule:
    - cron: "0 0 * * *" # 每天运行一次
  workflow_dispatch: # 允许手动触发

jobs:
  sync-and-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # 获取完整历史记录

      - name: Configure Git
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

      - name: Add Upstream Remote
        run: git remote add upstream https://github.com/morytyann/OpenWrt-mihomo.git

      - name: Fetch Upstream
        run: git fetch upstream

      - name: Sync Upstream Changes
        run: |
          CURRENT_BRANCH=$(git rev-parse --abbrev-ref HEAD)
          git checkout -B sync-upstream $CURRENT_BRANCH
          git merge -X theirs --no-commit --no-ff upstream/main

      - name: Restore Ignored Files and Directories
        run: |
          git checkout HEAD -- mihomo/Makefile luci-app-mihomo/Makefile
          git restore --staged mihomo/Makefile luci-app-mihomo/Makefile
          git checkout HEAD -- .github/workflows
          git restore --staged .github/workflows

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: Sync upstream changes
          title: Sync changes from upstream repository
          body: |
            This PR syncs changes from the upstream repository.

            Ignored files and directories:
            - mihomo/Makefile
            - luci-app-mihomo/Makefile
            - .github/workflows/
          branch: sync-upstream
          delete-branch: true
          base: ${{ github.ref }}
