name: Sync Upstream and Create PR

on:
  schedule:
    - cron: "0 17 * * *" # 每天运行一次
  workflow_dispatch: # 允许手动触发

jobs:
  sync-upstream:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name 'GitHub Actions'
          git config user.email 'actions@github.com'

      - name: Fetch Upstream
        run: |
          git remote add upstream https://github.com/morytyann/OpenWrt-mihomo.git
          git fetch upstream

      - name: Merge Upstream
        run: |
          git merge -X theirs upstream/main --no-edit
          git status

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          title: "Sync: Merge upstream changes"
          body: "This PR syncs changes from the upstream repository while preserving our local modifications as specified in .gitattributes."
          branch: sync-upstream
          base: Alpha
