name: Sync Upstream and Create PR

on:
  schedule:
    - cron: "0 17 * * *" # 每天运行一次
  workflow_dispatch: # 允许手动触发

jobs:
  sync-upstream:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name 'GitHub Actions'
          git config user.email 'actions@github.com'

      - name: Add Upstream Remote
        run: git remote add upstream https://github.com/morytyann/OpenWrt-mihomo.git

      - name: Fetch Upstream
        run: git fetch upstream

      - name: Sync with Upstream
        run: |
          git merge upstream/main --no-edit
          git status

      - name: Reset Excluded Files and Directory
        run: |
          git checkout HEAD -- mihomo/Makefile
          git checkout HEAD -- luci-app-mihomo/Makefile
          git checkout HEAD -- .github/workflows/

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          title: "Sync: Merge upstream changes"
          body: "Automated PR to sync changes from the upstream repository"
          branch: sync-upstream
          base: Alpha
