name: Sync Upstream and Create PR

on:
  schedule:
    - cron: "0 0 * * *" # 每天运行一次
  workflow_dispatch: # 允许手动触发

jobs:
  sync-upstream:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

      - name: Add Upstream Remote
        run: git remote add upstream https://github.com/morytyann/OpenWrt-mihomo.git

      - name: Fetch Upstream
        run: git fetch upstream

      - name: Create and Switch to Sync Branch
        run: git checkout -b sync-upstream

      - name: Merge Upstream
        run: |
          git read-tree -mu HEAD upstream/main
          git reset upstream/main -- mihomo/Makefile luci-app-mihomo/Makefile .github/workflows
          git checkout -- mihomo/Makefile luci-app-mihomo/Makefile
          git add .
          git diff-index --quiet HEAD || git commit -m "Sync: Merge changes from upstream repository"

      - name: Push Changes
        run: git push origin sync-upstream --force

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: sync-upstream
          base: Alpha
          title: "Sync: Merge upstream changes"
          body: "Automated PR to sync changes from upstream repository"
          delete-branch: true
