name: Sync Upstream

on:
  schedule:
    - cron: "0 0 * * *" # 每天运行一次
  workflow_dispatch: # 允许手动触发

jobs:
  sync-upstream:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

      - name: Add Upstream Remote
        run: |
          git remote add upstream https://github.com/morytyann/OpenWrt-mihomo.git

      - name: Fetch Upstream
        run: |
          git fetch upstream

      - name: Switch to Target Branch
        run: |
          git checkout Alpha

      - name: Merge Upstream
        run: |
          git merge upstream/main -X ours --no-commit --no-ff

      - name: Restore Excluded Files
        run: |
          git checkout HEAD -- mihomo/Makefile
          git checkout HEAD -- luci-app-mihomo/Makefile
          git checkout HEAD -- .github/workflows/sync_upstream.yml
          git checkout HEAD -- .github/workflows/update_mihomo_package_hash.yml
          git checkout HEAD -- .github/workflows/build.yml
          git checkout HEAD -- .github/workflows/release.yml

      - name: Check for Changes
        id: check_changes
        run: |
          if git diff --quiet && git diff --staged --quiet; then
            echo "changes_made=false" >> $GITHUB_OUTPUT
          else
            echo "changes_made=true" >> $GITHUB_OUTPUT
          fi

      - name: Create Pull Request
        if: steps.check_changes.outputs.changes_made == 'true'
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: Sync upstream changes
          title: Sync Upstream Changes
          body: |
            This PR syncs changes from the upstream repository.

            Automated changes by GitHub Actions.
          branch: sync-upstream-changes
          base: Alpha # 目标分支，保持与之前相同
          delete-branch: true

      - name: Check PR Status
        if: steps.check_changes.outputs.changes_made == 'true'
        run: |
          echo "Pull Request created successfully."

      - name: No Changes
        if: steps.check_changes.outputs.changes_made == 'false'
        run: |
          echo "No changes were made. The repository is already up to date."
