name: Sync Upstream and Create PR

on:
  schedule:
    - cron: "0 0 * * *" # 每天UTC时间00:00运行
  workflow_dispatch: # 允许手动触发

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

      - name: Add Upstream Remote
        run: git remote add upstream https://github.com/morytyann/OpenWrt-mihomo.git

      - name: Fetch Upstream
        run: git fetch upstream

      - name: Merge Upstream
        run: |
          git merge upstream/main --no-commit --no-ff
          git reset -- mihomo/Makefile luci-app-mihomo/Makefile
          git checkout -- mihomo/Makefile luci-app-mihomo/Makefile
          git rm -r --cached .github/workflows
          git checkout -- .github/workflows

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: Sync upstream changes
          title: Sync changes from upstream repository
          body: |
            This PR syncs changes from the upstream repository.

            Changes have been merged excluding:
            - mihomo/Makefile
            - luci-app-mihomo/Makefile
            - .github/workflows directory
          branch: sync-upstream
          delete-branch: true
          base: Alpha
