name: Update Mihomo Package Hash

on:
  schedule:
    - cron: "0 0 * * *" # 每天运行
  workflow_dispatch: # 允许手动触发

jobs:
  update-package:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get latest commit hash
        id: get_hash
        run: |
          git clone https://github.com/MetaCubeX/mihomo.git mihomo_core
          cd mihomo_core
          LATEST_HASH=$(git rev-parse HEAD)
          echo "LATEST_HASH=$LATEST_HASH" >> $GITHUB_OUTPUT

      - name: Generate source archive
        run: |
          cd mihomo_core
          mkdir -p compress
          git archive --format=tar.gz --output=compress/mihomo-${LATEST_HASH:0:8}.tar.gz HEAD
        env:
          LATEST_HASH: ${{ steps.get_hash.outputs.LATEST_HASH }}

      - name: Calculate MIRROR_HASH
        id: calc_hash
        run: |
          MIRROR_HASH=$(sha256sum mihomo_core/compress/mihomo-${LATEST_HASH:0:8}.tar.gz | awk '{print $1}')
          echo "MIRROR_HASH=$MIRROR_HASH" >> $GITHUB_OUTPUT
        env:
          LATEST_HASH: ${{ steps.get_hash.outputs.LATEST_HASH }}

      - name: Update Makefile
        run: |
          sed -i "s/PKG_SOURCE_VERSION:=.*/PKG_SOURCE_VERSION:=$LATEST_HASH/" Makefile
          sed -i "s/PKG_MIRROR_HASH:=.*/PKG_MIRROR_HASH:=$MIRROR_HASH/" Makefile
        env:
          LATEST_HASH: ${{ steps.get_hash.outputs.LATEST_HASH }}
          MIRROR_HASH: ${{ steps.calc_hash.outputs.MIRROR_HASH }}

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: Update Mihomo package Hash to latest version
          title: Update Mihomo package Hash
          body: |
            This PR updates the Mihomo package Hash to the latest version.
            - PKG_SOURCE_VERSION: ${{ steps.get_hash.outputs.LATEST_HASH }}
            - PKG_MIRROR_HASH: ${{ steps.calc_hash.outputs.MIRROR_HASH }}
          branch: update-mihomo-package-hash
